<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb.odm.default_document_manager' shared service.

include_once $this->targetDirs[3].'\\vendor\\doctrine\\mongodb-odm-bundle\\ManagerConfigurator.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\common\\lib\\Doctrine\\Common\\Persistence\\ObjectManager.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\mongodb-odm\\lib\\Doctrine\\ODM\\MongoDB\\DocumentManager.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\common\\lib\\Doctrine\\Common\\EventManager.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\doctrine-bridge\\ContainerAwareEventManager.php';

$this->services['doctrine_mongodb.odm.default_document_manager'] = $instance = \Doctrine\ODM\MongoDB\DocumentManager::create(($this->services['doctrine_mongodb.odm.default_connection'] ?? $this->load('getDoctrineMongodb_Odm_DefaultConnectionService.php')), ($this->privates['doctrine_mongodb.odm.default_configuration'] ?? $this->load('getDoctrineMongodb_Odm_DefaultConfigurationService.php')), ($this->privates['doctrine_mongodb.odm.default_connection.event_manager'] ?? $this->privates['doctrine_mongodb.odm.default_connection.event_manager'] = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this)));

(new \Doctrine\Bundle\MongoDBBundle\ManagerConfigurator(array()))->configure($instance);

return $instance;
