<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb.odm.default_connection' shared service.

include_once $this->targetDirs[3].'\\vendor\\doctrine\\mongodb\\lib\\Doctrine\\MongoDB\\Connection.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\common\\lib\\Doctrine\\Common\\EventManager.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\doctrine-bridge\\ContainerAwareEventManager.php';

return $this->services['doctrine_mongodb.odm.default_connection'] = new \Doctrine\MongoDB\Connection($this->getEnv('MONGODB_URL'), array(), ($this->privates['doctrine_mongodb.odm.default_configuration'] ?? $this->load('getDoctrineMongodb_Odm_DefaultConfigurationService.php')), ($this->privates['doctrine_mongodb.odm.default_connection.event_manager'] ?? $this->privates['doctrine_mongodb.odm.default_connection.event_manager'] = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this)), array());
