<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_mongodb.odm.hydrator_cache_warmer' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\CacheWarmer\\CacheWarmerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\mongodb-odm-bundle\\CacheWarmer\\HydratorCacheWarmer.php';

return $this->privates['doctrine_mongodb.odm.hydrator_cache_warmer'] = new \Doctrine\Bundle\MongoDBBundle\CacheWarmer\HydratorCacheWarmer($this);
