<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXFDhxBc\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXFDhxBc/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXFDhxBc.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXFDhxBc\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXFDhxBc\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XFDhxBc',
    'container.build_id' => '63600dc0',
    'container.build_time' => 1528630841,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXFDhxBc');
